### PR TITLE
Added dev.distributed.press ansibles

### PR DESCRIPTION
**Pull request by ASoTNetworks**

### CODE REVIEW

**Comment by benhylau** [comment]
Is there no way to reuse files? This clones everything, which also means when we make a change we'd have to change it in two files. Is this standard for ansible?

**Comment by ASoTNetworks** [comment]
I think there is a way to do it have to look into it.

**Comment by benhylau** [comment]
Any update on this?

**Comment by YurkoWasHere** [comment]
Working on creating per-host configuration. Once PR is merged we can easily add dev

https://github.com/hyphacoop/ansibles/pull/19/files

**Comment by YurkoWasHere** [comment]
**TODO**

- [ ] Finish of this PRs
https://github.com/hyphacoop/ansibles/pull/20
🔽 Merge to 
https://github.com/hyphacoop/ansibles/pull/19

- [ ] Migrate Configurations
From
https://github.com/hyphacoop/ansibles/pull/18
configurations to 
https://github.com/hyphacoop/ansibles/pull/19

- [ ] Test and merge to master

**Comment by LexaMichaelides** [comment]
@YurkoWasHere - can this PR be merged and closed? Or should it just be closed? I'm cleaning up our issue board but don't want to close a PR if I don't know what it is.

**Comment by YurkoWasHere** [comment]
2021 if it wasnt pulled its prob not needed

**Pull request closed without merging**
